- name: configure and setup matrix
  include_tasks:
    file: matrix.yml
    apply:
      tags:
        - matrix
  tags:
    - matrix

- name: configure and setup nginx
  include_tasks:
    file: nginx.yml
    apply:
      tags:
        - nginx
  tags:
    - nginx

- name: run the matrix stack with docker-compose
  include_tasks:
    file: run.yml
    apply:
      tags:
        - run
  tags:
    - run
