- name: Deploy matrix
  include_tasks:
    file: matrix.yml
    apply:
      tags:
        - matrix
  tags:
    - matrix

- name: Deploy nginx
  include_tasks:
    file: nginx.yml
    apply:
      tags:
        - nginx
  tags:
    - nginx
