- name: "Create the {{ matrix_stack_install_path }} if it does not exist"
  ansible.builtin.file:
    path: "{{ matrix_stack_install_path }}"
    state: directory
    mode: '0755'

- name: Create the homeserver config file
  ansible.builtin.template:
    src: templates/homeserver.yaml
    dest: "{{ matrix_stack_install_path }}/synapse_data/homeserver.yaml"

- name: Ensure that the media store folder is writtable by synapse
  ansible.builtin.file:
    path: "{{ matrix_stack_install_path }}/synapse_data/media_store"
    state: directory
    owner: 991
    group: 991
    mode: '0755'

- name: Create the element config file
  ansible.builtin.template:
    src: templates/config.json
    dest: "{{ matrix_stack_install_path }}/element/config.json"

- name: Create the mautrix-telegram config file
  ansible.builtin.template:
    src: templates/mautrix-telegram.yaml
    dest: "{{ matrix_stack_install_path }}/synapse_data/mautrix-telegram/config.yaml"
