- name: "Create the {{ matrix_stack_install_path }}/nginx directories"
  ansible.builtin.file:
    path: "{{ matrix_stack_install_path }}/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - nginx
    - nginx/data
    - nginx/data/conf
    - nginx/data/ssl
    - nginx/well-known

- name: Create the nginx default home page
  ansible.builtin.template:
    src: templates/nginx/index.html
    dest: "{{ matrix_stack_install_path }}/nginx/data/index.html"

- name: Create the nginx configuration
  ansible.builtin.template:
    src: templates/nginx/default.conf
    dest: "{{ matrix_stack_install_path}}/nginx/data/conf/default.conf"

- name: Create well-known folder with client / server files
  ansible.builtin.template:
    src: "templates/nginx/well-known/{{ item }}"
    dest: "{{ matrix_stack_install_path }}/nginx/well-known/matrix/{{ item }}"
  with_items:
    - client
    - server

- name: Create the SSL/TLS certificate
  # https://certbot.eff.org/instructions?ws=nginx&os=ubuntufocal
  # https://hub.docker.com/r/certbot/certbot
  debug:
    msg: "TODO!"
